
language: ruby

git:
  depth: 1

branches:
  only:
  - master

cache:
  bundler: true
  directories:
    - $HOME/.ipfs/
    - $HOME/repo/

install:
  - bundle install
  - wget https://dist.ipfs.io/go-ipfs/v0.4.19/go-ipfs_v0.4.19_linux-amd64.tar.gz -O /tmp/ipfs.tar.gz
  - cd /tmp/ && tar -xvf /tmp/ipfs.tar.gz && cd -
  - sudo cp /tmp/go-ipfs/ipfs /usr/local/bin/

before_script:
  - bundle exec rake init --quiet
  - openssl aes-256-cbc -K $encrypted_bc929740312b_key -iv $encrypted_bc929740312b_iv -in ./key.enc -out ~/.ipfs/keystore/key -d
  - ipfs daemon &

script: bundle exec rake deploy --quiet

stages:
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
  - "22"
  - "23"
  - "24"
  - "25"
  - "26"
  - "27"
  - "28"
  - "29"
  - "30"
  - "31"
  - "32"
  - "33"
  - "34"
  - "35"
  - "36"
  - "37"
  - "38"
  - "39"
  - "40"
  - "41"
  - "42"
  - "43"
  - "44"
  - "45"
  - "46"
  - "47"
  - "48"

jobs:  
  include:
    - stage: "1"
    - stage: "2"
    - stage: "3"
    - stage: "4"
    - stage: "5"
    - stage: "6"
    - stage: "7"
    - stage: "8"
    - stage: "9"
    - stage: "10"
    - stage: "11"
    - stage: "12"
    - stage: "13"
    - stage: "14"
    - stage: "15"
    - stage: "16"
    - stage: "17"
    - stage: "18"
    - stage: "19"
    - stage: "20"
    - stage: "21"
    - stage: "22"
    - stage: "23"
    - stage: "24"
    - stage: "25"
    - stage: "26"
    - stage: "27"
    - stage: "28"
    - stage: "29"
    - stage: "30"
    - stage: "31"
    - stage: "32"
    - stage: "33"
    - stage: "34"
    - stage: "35"
    - stage: "36"
    - stage: "37"
    - stage: "38"
    - stage: "39"
    - stage: "40"
    - stage: "41"
    - stage: "42"
    - stage: "43"
    - stage: "44"
    - stage: "45"
    - stage: "46"
    - stage: "47"
    - stage: "48"

after_success:
  - bundle exec rake sync[10] --quiet
  - bundle exec rake test --quiet
  - bundle exec rake sync[20] --quiet
